name: your_app_name
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences: ^2.2.2


flutter:
  uses-material-design: true
  assets:
    - assets/seed1_c.png
    - assets/seed2_c.png
    - assets/seed3_c.png



